# Generated by Django 5.0.1 on 2024-02-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_superadmin',
            new_name='is_superuser',
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=333, unique=True),
        ),
    ]
