# Generated by Django 5.0.1 on 2024-02-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
        ('category', '0003_alter_category_slug'),
    ]

    operations = [
    ]
